// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_WwVjk3Eti4Wrgwhkaykz-9eMmD4Vj1I',
    appId: '1:379466219783:web:b0b0e93036dbe7fbf405a2',
    messagingSenderId: '379466219783',
    projectId: 'cravit-239b3',
    authDomain: 'cravit-239b3.firebaseapp.com',
    storageBucket: 'cravit-239b3.firebasestorage.app',
    measurementId: 'G-74TLH46YNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0BiqL7pcKiS92-dLNw_K-X1fS5FALmew',
    appId: '1:379466219783:android:8a8e53ed9ddfb95bf405a2',
    messagingSenderId: '379466219783',
    projectId: 'cravit-239b3',
    storageBucket: 'cravit-239b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgjy5Ex06fk0FJFGQWutCchJDpE8oDFM',
    appId: '1:379466219783:ios:f4a71d060812de84f405a2',
    messagingSenderId: '379466219783',
    projectId: 'cravit-239b3',
    storageBucket: 'cravit-239b3.firebasestorage.app',
    androidClientId: '379466219783-74kup6n2g4f6afsdpkjs0t4hdmuv3liq.apps.googleusercontent.com',
    iosClientId: '379466219783-q6ilefkvarnpookpq4hfub6bhqvtv55v.apps.googleusercontent.com',
    iosBundleId: 'com.cravit.seller.sellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgjy5Ex06fk0FJFGQWutCchJDpE8oDFM',
    appId: '1:379466219783:ios:f4a71d060812de84f405a2',
    messagingSenderId: '379466219783',
    projectId: 'cravit-239b3',
    storageBucket: 'cravit-239b3.firebasestorage.app',
    androidClientId: '379466219783-74kup6n2g4f6afsdpkjs0t4hdmuv3liq.apps.googleusercontent.com',
    iosClientId: '379466219783-q6ilefkvarnpookpq4hfub6bhqvtv55v.apps.googleusercontent.com',
    iosBundleId: 'com.cravit.seller.sellerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_WwVjk3Eti4Wrgwhkaykz-9eMmD4Vj1I',
    appId: '1:379466219783:web:9507eba88cc6bc70f405a2',
    messagingSenderId: '379466219783',
    projectId: 'cravit-239b3',
    authDomain: 'cravit-239b3.firebaseapp.com',
    storageBucket: 'cravit-239b3.firebasestorage.app',
    measurementId: 'G-55VYEJBNHC',
  );
}
